# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBJnVqxgwqz_2qoR_y_yYO2noNPDGj6b
"""

# dashboard_bike_sharing.py

!pip install streamlit
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st # Import the streamlit library

# Set tema style seaborn
sns.set(style='whitegrid')

# Judul halaman
st.title("🚲 Bike Sharing Analysis Dashboard")
st.subheader("Analisis Pengaruh Cuaca dan Musim terhadap Jumlah Peminjaman Sepeda")

# Load dataset
@st.cache_data
def load_data():
    df = pd.read_csv("day.csv")  # pastikan file ada di direktori yang sama
    df['dteday'] = pd.to_datetime(df['dteday'])

    # Mapping label kategori
    season_dict = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'}
    weekday_dict = {0: 'Sun', 1: 'Mon', 2: 'Tue', 3: 'Wed', 4: 'Thu', 5: 'Fri', 6: 'Sat'}
    weathersit_dict = {
        1: 'Clear/Few clouds',
        2: 'Mist/Cloudy',
        3: 'Light Snow/Rain',
        4: 'Heavy Rain/Snow'
    }

    df['season'] = df['season'].map(season_dict)
    df['weekday'] = df['weekday'].map(weekday_dict)
    df['weathersit'] = df['weathersit'].map(weathersit_dict)
    df['year'] = df['dteday'].dt.year
    df['month'] = df